# Generated by Django 3.2.3 on 2021-05-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=400)),
                ('img', models.URLField(max_length=500)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
