# Generated by Django 3.2.3 on 2021-06-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('external_url', models.URLField(blank=True, default='', max_length=500, null=True)),
                ('attributes', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
